- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/enhancement.md
- .github/ISSUE_TEMPLATE/failing-test.md
- .github/ISSUE_TEMPLATE/question.md
- .github/workflows/main.yaml
- Makefile
1. add actions
2. add issue templates
> add actions and issue templates

- pkg/controller/global.go
- pkg/networking/servicediscovery/serviceproxy/serviceproxy.go
- pkg/networking/servicediscovery/serviceproxy/serviceproxy_test.go
- pkg/networking/trafficplugin/protocol/tcp/tcp.go
- pkg/networking/trafficplugin/registry/registry.go
/kind bug
Problems with accessing external services through edgemesh at the edge
Which issue(s) this PR fixes:
Fixes #10
Special notes for your reviewer:
git squash
Does this PR introduce a user-facing change?:
> fix: pull in external services through endpoints

- agent/cmd/edgemesh-agent/app/server.go
- agent/pkg/chassis/registry/registry.go
- agent/pkg/gateway/controller/controller.go
- agent/pkg/proxy/proxy.go
- agent/pkg/tunnel/module.go
- agent/pkg/tunnel/tunnel.go
- build/agent/kubernetes/edgemesh-agent/03-configmap.yaml
- build/agent/kubernetes/edgemesh-gateway/03-configmap.yaml
> refactor edge gateway and transport http through tcp in feature cross lan communication

- .golangci.yml
- agent/cmd/edgemesh-agent/app/config/validation/validation.go
- agent/pkg/chassis/loadbalancer/consistenthash/hashring/cache.go
- agent/pkg/chassis/protocol/tcp/tcp.go
- agent/pkg/chassis/registry/registry.go
- agent/pkg/proxy/controller/controller.go
- agent/pkg/tunnel/protocol/tcp/tcpproxy.go
- common/constants/default.go
Sync from `kubeedge/kubeedge`.
Signed-off-by: Long <long0dai@foxmail.com>
> ci: add lint config

- agent/pkg/proxy/proxy.go
Signed-off-by: gy95 <1015105054@qq.com>
fix possible agent_proxy resource leak: where to release resource(close connection or file) should be modified.
> fix possible agent_proxy resource leak

- agent/cmd/edgemesh-agent/app/config/config.go
- build/agent/kubernetes/edgemesh-agent/03-configmap.yaml
- build/agent/kubernetes/edgemesh-gateway/03-configmap.yaml
- common/informers/informers.go
> [#47]:bug:Bugfix:Secret cannot be updated when edgemesh-agent is started

- agent/pkg/proxy/iptables.go
bugfix: Failed to watch xxx: failed to list xxx net/http: TLS handshake timeout #59
> bugfix: Failed to watch xxx: failed to list xxx net/http: TLS handshake timeout #59

- agent/pkg/proxy/iptables.go
- go.sum
exclude the services that is kube-dns or coredns
> validate the kube-dns is nil AND add ignore rules from coredns

- agent/pkg/proxy/iptables.go
/kind bug
Problems with accessing external services through edgemesh at the edge
Which issue(s) this PR fixes:
Fixes #67
#66 (comment)
Special notes for your reviewer:
1. The ignoreRulesIptablesEnsureMap used for heavy processing was added to the createIgnoreRules function before, and there is a for range reference problem;
2. Added a label: proxyby=edgemesh for services that require cloud-side communication. The intent is that services without this label still use kube-proxy for routing;
3. In the EnsureRules function, the process of re-refresh creation of ignoring rules and proxy rules has been added, otherwise changes over time may lead to untimely route refresh and increase the load of edgemesh;
4. The ignoreRuleByService is …
> Added a label: proxyby=edgemesh for services that require cloud-side communication.

- agent/pkg/chassis/registry/registry.go
fix handle l4 proxy err : lb: service xxx has no instances, refer to issue #74
> fix handle l4 proxy err

- CONTRIBUTING.md
- README.md
- README_zh.md
- docs/contribute/contributing-guide.md
- docs/contribute/developer-guide.md
EdgeMesh project does not have any contributing and developer guide yet, add contributing and developer guide files to help the contributors.
> docs: add contributing and developer guide files

- docs/.vuepress/configs/navbar/en.ts
- docs/.vuepress/configs/navbar/zh.ts
- docs/.vuepress/configs/sidebar/en.ts
- docs/.vuepress/configs/sidebar/zh.ts
- docs/advanced/hybirdnat.md
- docs/zh/advanced/hybirdnat.md
Add the edgemesh + kube-proxy hybird deploy simple docs
> Add the edgemesh + kube-proxy hybird deploy simple docs

- examples/cloudzone.yaml
- examples/edgezone.yaml
- examples/hostname-lb-random.yaml
- examples/hostname.yaml
- examples/tcp-echo-service.yaml
- examples/websocket.yaml
>     Delete the specified node name and add node affinity.
>     Modify node affinity.
>     Modify yaml file.
>     Use node affinity instead of specifying the node name.
The PR I submitted just wanted to modify the yaml file of version 1.8
> Submit yaml file of deployment type.

- build/agent/kubernetes/edgemesh-gateway/03-deployment.yaml
- docs/guide/edge-gateway.md
- docs/guide/getting-started.md
- docs/guide/test-case.md
- docs/zh/guide/edge-gateway.md
- docs/zh/guide/getting-started.md
- docs/zh/guide/test-case.md
- examples/cloudzone.yaml
- examples/edgezone.yaml
- examples/hostname.yaml
fix issue:
#98 
#99 
#100 
#101 
#102 
#103 
#104 
#106 
#108
> fix some docs issue

- tests/e2e/k8s/tools.go
- tests/e2e/traffic/testsuite.go
- tests/e2e/traffic/traffic_test.go
delete the hostport config in edge pod and update the retrytime to 3
Refs #87
> ci: improve e2e code

- agent/pkg/chassis/protocol/http/http.go
- agent/pkg/chassis/protocol/tcp/handler.go
- agent/pkg/chassis/protocol/tcp/tcp.go
- agent/pkg/gateway/controller/controller.go
- agent/pkg/proxy/proxy.go
/kind bug
Enable users to have the ability to access pods using session-persistence.
> support traffic governance using HTTP

- agent/pkg/proxy/protocol/protocol.go
I think const is better than the magic number
> use const instead the magic number

- Makefile
- hack/lib/buildx.sh
- hack/make-rules/push.sh
> support push docker images for multi architectures

- agent/pkg/chassis/controller/controller.go
It's better to add  lock while deleting hash ring.
> add lock while deleting hash ring

- common/util/util.go
I think const is better than a string
> use const instead the string

- agent/pkg/dns/config/config.go
- agent/pkg/gateway/config/config.go
- agent/pkg/proxy/config/config.go
- agent/pkg/tunnel/config/config.go
> fix some default value

- agent/cmd/edgemesh-agent/app/config/config.go
Use constant for edge ApiServer.
> use constant for edge ApiServer

- server/cmd/edgemesh-server/app/server.go
Through validate, we already know the detailed error. So I replace klog.Fatal with klog.Exit here.
> replace klog.Fatal with klog.Exit

- agent/pkg/proxy/iptables.go
- agent/pkg/proxy/proxy.go
Signed-off-by: lvchenggang <lvchenggang_yewu@cmss.chinamobile.com>
Fix some grammar problems in proxy module.
> Grammar fix in proxy module

- server/pkg/tunnel/config/config.go
> remove '0.0.0.0' for publicIP 

- common/util/util.go
> remove GetPodsSelector

- agent/pkg/chassis/config/config.go
- agent/pkg/chassis/install.go
- agent/pkg/tunnel/config/config.go
- agent/pkg/tunnel/module.go
- common/acl/camanager.go
- common/util/util.go
- server/pkg/tunnel/config/config.go
- server/pkg/tunnel/module.go
when print defaultConfig no longer read from env，and get nodeName from env only once
> when print defaultConfig no longer read from env，and get nodeName from env only once

- agent/pkg/dns/dns.go
- docs/.vuepress/config.ts
- docs/guide/getting-started.md
- docs/zh/guide/getting-started.md
> edgedns no longer writes nameserver to host's /etc/resolv.conf

- agent/pkg/chassis/controller/controller.go
- agent/pkg/chassis/registry/registry.go
- build/agent/Dockerfile
- build/server/Dockerfile
- hack/lib/buildx.sh
- hack/lib/init.sh
1. when addr.TargetRef is empty, addr.IP is used as the instanceName
2. reference makefile in dockerfile to build executable file
> use make in dockerfile to build executable file

- examples/cloudzone.yaml
- examples/edgezone.yaml
- examples/tcp-echo-service.yaml
poorunga/go-echo can support arm64 and amd64 CPU arch.
> tcp test image is replaced with poorunga/go-echo

- .github/workflows/main.yaml
Signed-off-by: khalid-jobs <qinkai1994@qq.com>
> refactor: use action step to setup helm

- common/security/camanager.go
/kind enhancement
add detail log when failed to send a http request
Fixes #
```release-note
```
> add detail log when failed to send a http request

- common/security/manager.go
remove unnecessaries in function NewManager
> optimize NewManager function

- build/agent/Dockerfile
- build/agent/iptables-wrapper
fix issue: #30 
This solution is based on kube-proxy fix to the same issue:
https://github.com/kubernetes/kubernetes/pull/82966
> add ability to detect iptables mode in edgemesh-agent image

- agent/pkg/chassis/controller/controller.go
- agent/pkg/gateway/controller/controller.go
- agent/pkg/tunnel/controller/controller.go
- common/informers/informers.go
- server/pkg/tunnel/controller/controller.go
> no need to run informers in manager

- examples/cloudzone.yaml
- examples/edgezone.yaml
> update match label in cloudzone and edgezone examples

- common/constants/default.go
- common/util/util.go
use camel case instead of snake case
> use camel case instead of snake case

- agent/pkg/proxy/socks5_proxy.go
Signed-off-by: chengengkun <1366542563@qq.com>
> fix-328: ssh_exchange_identification: Connection closed by remote host

- third_party/forked/kubernetes/pkg/proxy/userspace/loadbalancer_ex.go
- third_party/forked/kubernetes/pkg/proxy/userspace/loadbalancer_strategy.go
fix hashKey in proxy loadbalancer when key type is UserSourceIP
> fix hashKey in proxy loadbalancer when key type is UserSourceIP

- docs/advanced/architecture.md
- docs/zh/advanced/architecture.md
Signed-off-by: dapengJacky peng.chen@daocloud.io
/kind doc
doc: update architecture.md image link
> doc:update architecture.md image link

- README.md
- README_zh.md
Signed-off-by: wackxu <xushiwei5@huawei.com>
/kind clean-up
/assign @Poorunga
> fix not found link

- pkg/tunnel/tunnel.go
> add tunnel module comments

- pkg/tunnel/tunnel.go
/kind bug
/assign @Poorunga
fix tryDialEndpoint  function constant usage errors
> fix tunnel tryDialEndpoint constant usage errors

- pkg/tunnel/module.go
- pkg/tunnel/tunnel.go
1. Configure ForceReachabilityPrivate when relayMap does not contain public IP
2. No longer delete the relays that cannot be connected in the bootstrap stage, and ensure that those relays can still be connected in the heartbeat stage
> configure ForceReachabilityPrivate when relayMap does not contain public IP

- pkg/tunnel/tunnel.go
- pkg/util/net/conn.go
> Relay nodes must run normally, so circuit address should be set to permanent

- pkg/dns/corefile.go
- pkg/dns/module.go
- pkg/gateway/module.go
- pkg/proxy/module.go
- pkg/tunnel/module.go
> Optimize code comments and code logs

- docs/proposal/edgemesh-security-proposal.md
- docs/proposal/edgemesh-ssh-proposal.md
> Fix  proposal spelling error

- .github/workflows/docs.yml
- .github/workflows/main.yaml
- .github/workflows/release-helm-package.yaml
/kind bug
Fixes #
https://github.com/kubeedge/edgemesh/issues/476
```release-note
```
> Fix Install Go CI error

- cmd/edgemesh-agent/app/options/options.go
- cmd/edgemesh-gateway/app/options/options.go
- pkg/apis/config/defaults/default.go
/kind cleanup
Fixes #
```release-note
```
> Optimization configfile path constant definition

- pkg/loadbalancer/hashring.go
/kind cleanup
Fixes #
```release-note
NONE
```
> specifies slice length

- pkg/tunnel/tunnel.go
/kind cleanup
Fixes #
```release-note
NONE
```
> update handle error

- pkg/loadbalancer/hashring.go
/kind bug
Fixes #
```release-note
```
> slice length fix

- pkg/gateway/util.go
kind featur
Fixes #
```release-note
```
> IPv4Mask instead the number 4

- docs/guide/edge-kube-api.md
- docs/zh/guide/edge-kube-api.md
> May use helm to install cloudcore,edge-kube-api.md modified

- cmd/edgemesh-agent/app/server.go
- pkg/apis/config/v1alpha1/default.go
/kind feature
Fixes #
```release-note
```
> Support get defaultEdgeMeshAgentMinConfig

- docs/proposal/edgemesh-ha-design-proposal.md
- docs/proposal/images/mesh-feature-ha/case1.svg
Correct some miss spell or format errors.
> Refine the words of the proposal.

- cmd/edgemesh-agent/app/server.go
- cmd/edgemesh-gateway/app/server.go
- pkg/apis/config/v1alpha1/types.go
- pkg/profile/profile.go
/kind feature
Fixes #
```release-note
```
> add pprof for agent and gateway

- CODE_OF_CONDUCT.md
https://github.com/kubeedge/community/issues/158
As a CNCF project, we need to follow CNCF Code of Conduct.
> add CNCF Code of Conduct

- docs/zh/guide/README.md
> Fix kubeEdge dependencies link error

- cmd/edgemesh-gateway/app/server.go
- pkg/tunnel/module.go
> The nodeName of edgemesh-gateway is added with a -gateway suffix

- pkg/cni/adapter.go
- pkg/util/tunutils/tun.go
Signed-off-by: Icarus9913 [icaruswu66@qq.com](mailto:icaruswu66@qq.com)
/kind cleanup
improve the CNI logs and optimize the codes
> optimize CNI logs and codes

- docs/proposal/edgemesh-cni-proposal-cn.md
- docs/proposal/edgemesh-cni-proposal-en.md
> update cni proposal

- docs/.vuepress/configs/sidebar/en.ts
- docs/.vuepress/configs/sidebar/zh.ts
> add cni to sidebar

- docs/guide/test-case.md
- docs/zh/guide/test-case.md
> fix testcase doc wrong link
