kubeedge/edgemesh

agent/pkg/chassis/loadbalancer/consistenthash/consistenthash.go, agent/pkg/dns/module.go, agent/pkg/tunnel/module.go
Signed-off-by: gy95 <1015105054@qq.com>
`Strategy` struct has `sync.Mutex` to protect slice `instances` read/write
And some codes don't lock mutex to protect read/write. So add missing lock
And `return s.instances[i], nil` also need lock, so refactor `pick` function to return instance directly
=> fix missing strategy lock

server/pkg/tunnel/tunnel.go
Signed-off-by: gy95 <1015105054@qq.com>
when update secrets failed, can't print success related logs: `"success update [%s] addr %v to secret", constants.ServerAddrName, t.Host.Addrs()` 
So need `return` the function
=> when error, cannot print success logs

agent/pkg/gateway/controller/controller.go
Signed-off-by: gy95 <1015105054@qq.com>
field `ipArray` of structure `Manager` is a slice,  also need lock to protect read/write, so add the lock at the entry of `AddGateway`
=> fix gateway controller lock

agent/pkg/dns/dns.go
Problem: When resolve a domain name like "svc-name", edgemesh cannot correctly work.
Expect: When resolve a domain name like "svc-name", edgemesh should treat it as "svc-name.default", just like kubernetes.
=> fix dns domain resolve bug

agent/pkg/chassis/protocol/http/http.go, agent/pkg/chassis/protocol/protocol.go, agent/pkg/chassis/protocol/tcp/tcp.go, agent/pkg/chassis/registry/registry.go, agent/pkg/proxy/controller/controller.go, agent/pkg/proxy/iptables.go
Signed-off-by: JingXiang <jingxiang@leinao.ai>
https://github.com/kubeedge/edgemesh/issues/173
=> fix edgemesh-agent proxy fetching protocol bug

agent/pkg/chassis/controller/controller.go, agent/pkg/chassis/loadbalancer/consistenthash/hashring/serviceinstance.go, agent/pkg/chassis/registry/registry.go
/kind bug
As shown below，podIP can be same, but consistentHash use podIP as the key to get instance, so I choose PodName instead.
=> support consistentHash when pods distributed in different nodes in same podIP  

agent/pkg/proxy/controller/controller.go
For map 	ipBySvc , key should be svcNamespace.svcName instead of  svcName.svcNamespace
=> fix wrong annotation of map 	ipBySvc  

agent/pkg/tunnel/protocol/tcp/tcpproxy.go
For line 155, err euqals nil, meaninglessly, so is  line 162.
=> fix some errors for fmt.Errorf-statements

agent/pkg/chassis/registry/registry.go
We acquire instances from endpoint,  and endpoint itself is orderly, I think there is no need to use sort function.
=> delete unnecessary sort of microServiceInstances

agent/cmd/edgemesh-agent/app/config/config.go, agent/cmd/edgemesh-agent/app/server.go, build/agent/kubernetes/edgemesh-agent/05-configmap.yaml, build/agent/kubernetes/edgemesh-gateway/02-configmap.yaml, build/helm/edgemesh/charts/agent/values.yaml, build/helm/gateway/values.yaml
Befor: No matter the kubeAPIConfig.Master is set, it equals "http://127.0.0.1:10550" alwaysly.
Now：Only when the kubeAPIConfig.Master is not configured, it will be defaults.
=> If kubeAPIConfig is configured, the value prefer to user’s

agent/pkg/tunnel/controller/controller.go, agent/pkg/tunnel/protocol/tcp/tcpproxy.go
Signed-off-by: lvchenggang <lvchenggang_yewu@cmss.chinamobile.com>
Error strings of fmt.Errorf() should not be capitalized:
1) the IDE will prompt: "Error string should not be capitalized or end with punctuation".
2) since these logs are usually printed following other context, so with additional capital letters in log does not apply to logging.
=> Fix log's capitalization in tunnel module

README.md, README_zh.md, docs/guide/test-case.md, docs/zh/guide/test-case.md
1. The usage rules of destinationrule should be placed in the document, and users can understand its meaning only if it is placed close to the place where it is used.
2. The restriction on configuring the port name for the service has been removed.
---
1. destinationrule的使用规则应该放在文档中，只有放在靠近使用它的地方用户才能明白其含义
2. 给服务配置port name的限制已经去除了
=> delete the prerequisites part in the readme

agent/pkg/proxy/config/config.go, agent/pkg/proxy/module.go, agent/pkg/proxy/proxy.go, agent/pkg/proxy/socks5_proxy.go
Add a socks5 proxy to support cloud SSH login to the edge.
Documentation： [doc](https://github.com/kubeedge/edgemesh/issues/204)
Usage：
```
ssh -o "ProxyCommand nc --proxy-type socks5 --proxy {$edgemesh-ip}:10800 {$nodeName} {$port}" root@any-ip
```
edgemesh IP defaults to 169.254.96.16
=> add a socks5 proxy

agent/pkg/chassis/protocol/tcp/handler.go, agent/pkg/chassis/registry/registry.go
fix issue #168 
**Test Case**
1. Start a simple python http server:
```
$ python3 -m http.server
$ curl 192.168.0.229:8000
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>Directory listing for /</title>
</head>
<body>
<h1>Directory listing for /</h1>
<hr>
<ul>
......
```
192.168.0.229 is my node IP.
2. Create custom endpoints and service:
```
$ kubectl apply -f- <<EOF
kind: Endpoints
apiVersion: v1
metadata:
name: simple-http-server
subsets:
- addresses:
- ip: 192.168.0.229
ports:
- port: 8000
name: http-0
---
apiVersion: v1
kind: Service
metadata:
name: simple-http-server
spec:
ports:
- port: 8000
name: http-0
protocol: TCP
EOF
$ kubectl get all
NAME …
```
=> support access to external services through custom endpoints and services

docs/contribute/contributing-guide.md
The original link is not linked to the correct location
=> docs: change setup link to correct url

docs/advanced/hybirdnat.md, docs/guide/README.md, docs/zh/advanced/hybirdnat.md, docs/zh/guide/README.md
Because the filter label of kube-proxy is `service.kubernetes.io/service-proxy-name`, in order to unify the format, the filter label of edgemesh is changed to: `service.edgemesh.kubeedge.io/service-proxy-name`
=> modify the labels of services filtered by edgemesh

docs/guide/getting-started.md, docs/zh/guide/getting-started.md
Signed-off-by: zhaoyong <15261465531@163.com>
Because the original deployment document is getting started MD, the detection step is through the command kubectl get all - n kubeedge,
The results obtained make people uncertain whether edgemsh agent should be deployed on the cloud side, thinking that it will only be deployed on the edge node, which will lead to installation errors for new users
$kubectl get all -n kubeedge
NAME                                   READY   STATUS    RESTARTS   AGE
pod/edgemesh-agent-4rhz4               1/1     Running   0          76s
pod/edgemesh-agent-7wqgb               1/1     Running   0          76s
pod/edgemesh-agent-9c697               1/1     Running   0          76s
pod/edgemesh-server-5f6d5869ff-4568p   1/1     Running   0         5m8s
=> modify getting-started.md

agent/pkg/chassis/protocol/tcp/handler.go
=> Remove the code that closes defer rconn.Close()

build/agent/kubernetes/edgemesh-agent/05-daemonset.yaml, build/agent/kubernetes/edgemesh-gateway/05-deployment.yaml, examples/cloudzone.yaml, examples/edgezone.yaml, examples/tcp-echo-service.yaml
Signed-off-by: alongL <v6543210@gmail.com>
Well in Chinese mainland the network is always a problem.
Sometimes the image is hard to be pulled and have to be imported by docker.
Always imagePullPolicy makes some trouble.
So the imagePullPolicy IfNotPresent is very suitable. 
/assign @poorunga
=> change imagePullPolicy to IfNotPresent

third_party/forked/kubernetes/pkg/proxy/userspace/loadbalancer.go, third_party/forked/kubernetes/pkg/proxy/userspace/loadbalancer_ex.go, third_party/forked/kubernetes/pkg/proxy/userspace/loadbalancer_ex_test.go, third_party/forked/kubernetes/pkg/proxy/userspace/loadbalancer_strategy.go, third_party/forked/kubernetes/pkg/proxy/userspace/proxysocket.go
Issue: If there are more than one port in a service and the strategy is consistent hash, only the endpoints of the first port will be used to build the hash ring. Then if comes a request to another port, a wrong endpoint from the hash ring picked. #343 
Fix: cache loadbalance strategy for every service port and build the hash ring for every service port if the strategy is consistent hash.
=> pick a correct endpoint when there are more than one port in a service and strategy is consistent hash 

pkg/apis/config/defaults/default.go, pkg/apis/config/v1alpha1/default.go, pkg/apis/config/v1alpha1/types.go, pkg/tunnel/limit.go, pkg/tunnel/module.go
/kind feature Add libp2p stream limit settting
对libp2p stream扩展为默认可配置项
libp2p的resourcemanger默认的对所有的protocol进行流的限制。
[https://github.com/libp2p/go-libp2p/blob/master/p2p/host/resource-manager/limit_defaults.go](url)
参考源码，libp2p对protocol协议的限制主要分为以下两种:
1、针对协议的入栈出栈的流个数的限制
2、针对协议的每一个peer入栈出栈的流个数进行限制
最终针对协议的最终流个数限制为：
基础流个数+scale的扩展流个数。scale的扩展会根据每GB内存大小进行额外的扩容。
将基础流个数作为可配置项，并且设置为默认值，防止在中继过程中，遇到流被重置的问题。实测默认情况下，4-5个网页会触发stream reset。
=> Add libp2p stream limit settting

pkg/tunnel/module.go
/kind feature
libp2p默认情况下会针对relay server的时间和大小作限制。
根据:
[https://github.com/libp2p/go-libp2p/blob/master/p2p/protocol/circuitv2/relay/resources.go](url)
```
// DefaultLimit returns a RelayLimit object with the defaults filled in.
func DefaultLimit() *RelayLimit {
return &RelayLimit{
Duration: 2 * time.Minute,
Data:     1 << 17, // 128K
}
}
```
relay v2 server只能够维持2分钟的时间以及128K的数据大小，就会将此relay强制关闭。这对于视频流以及文件流传输是不合理的。建议将此配置为不作限制，或者作为默认可选项设置一个合理的数值
=> Cancel relay time limit

.github/workflows/main.yaml, .github/workflows/release.yaml
`release.yaml` is used to trigger the automatic published of the image when the code is merged into the main branch or when a tag is pushed. Refer to https://github.com/kubeedge/edgemesh/issues/413
=> add release.yaml

hack/update-image-tag.sh
`hack/update-image-tag.sh` can easily replace the tag for the image in yaml. Currently processing the following files:
- "${EDGEMESH_ROOT}/build/agent/resources/05-daemonset.yaml"
- "${EDGEMESH_ROOT}/build/gateway/resources/05-deployment.yaml"
- "${EDGEMESH_ROOT}/build/helm/edgemesh/values.yaml"
- "${EDGEMESH_ROOT}/build/helm/edgemesh-gateway/values.yaml"
=> add hack/update-image-tag.sh

go.mod, pkg/loadbalancer/loadbalancer.go
=> fix gateway serviceMap numbers sync error

pkg/loadbalancer/loadbalancer.go
=> add detail on the err log

docs/proposal/edgemesh-cni-proposal-cn.md
Signed-off-by: Icarus9913 [icaruswu66@qq.com](mailto:icaruswu66@qq.com)
/kind cleanup
improve the CNI proposal document
=> optimize the cni proposal document
